services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meu_banco #cria o banco de dados na hora da inicialização
    networks:
      - networks1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  back-end:
    build: . #uso a build ja criada no diretorio
    restart: always
    ports:
      -  "8081:8080"
    networks:
     - networks1
    depends_on:
      db:
        condition: service_healthy


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - networks1
    depends_on: #cria uma dependencia para o servidor do phpmyadmin funciona apenas com o db
      - db


networks:
  networks1:
    driver: bridge
